"""initial schema

Revision ID: 20260403_0001
Revises:
Create Date: 2026-04-07 15:26:50.192263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260403_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('upload_filename', sa.String(), nullable=True),
    sa.Column('total_assets', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overdue_bucket', sa.String(), nullable=True),
    sa.Column('recovered_status', sa.String(), nullable=True),
    sa.Column('inventory_bucket', sa.String(), nullable=True),
    sa.Column('legal_completeness', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('custom_rules_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('che300_model_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('displacement', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('guide_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('che300_model_id')
    )
    op.create_table('depreciation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('valuation', sa.Float(), nullable=True),
    sa.Column('prediction_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('management_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('role_level', sa.String(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('goal_category', sa.String(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_unit', sa.String(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('constraint_notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.String(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('total_ead', sa.Float(), nullable=False),
    sa.Column('total_book_value', sa.Float(), nullable=False),
    sa.Column('total_expected_loss', sa.Float(), nullable=False),
    sa.Column('total_expected_loss_rate', sa.Float(), nullable=False),
    sa.Column('total_expected_cash_30d', sa.Float(), nullable=False),
    sa.Column('total_expected_cash_90d', sa.Float(), nullable=False),
    sa.Column('total_expected_cash_180d', sa.Float(), nullable=False),
    sa.Column('total_provision_impact', sa.Float(), nullable=False),
    sa.Column('total_capital_impact', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_description', sa.String(), nullable=True),
    sa.Column('entry_date', sa.String(), nullable=True),
    sa.Column('overdue_amount', sa.Float(), nullable=True),
    sa.Column('che300_value', sa.Float(), nullable=True),
    sa.Column('daily_parking', sa.Float(), nullable=True),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('path_a_json', sa.Text(), nullable=True),
    sa.Column('path_b_json', sa.Text(), nullable=True),
    sa.Column('path_c_json', sa.Text(), nullable=True),
    sa.Column('path_d_json', sa.Text(), nullable=True),
    sa.Column('path_e_json', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('best_path', sa.String(), nullable=True),
    sa.Column('report_pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('che300_model_id', sa.String(), nullable=False),
    sa.Column('registration_date', sa.String(), nullable=False),
    sa.Column('query_date', sa.String(), nullable=False),
    sa.Column('city_code', sa.String(), nullable=True),
    sa.Column('excellent_price', sa.Float(), nullable=True),
    sa.Column('good_price', sa.Float(), nullable=True),
    sa.Column('medium_price', sa.Float(), nullable=True),
    sa.Column('fair_price', sa.Float(), nullable=True),
    sa.Column('dealer_buy_price', sa.Float(), nullable=True),
    sa.Column('dealer_sell_price', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('che300_model_id', 'registration_date', 'query_date', 'city_code', name='uq_valuation_cache_lookup')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('car_description', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('first_registration', sa.String(), nullable=True),
    sa.Column('gps_online', sa.Integer(), nullable=True),
    sa.Column('insurance_lapsed', sa.Integer(), nullable=True),
    sa.Column('ownership_transferred', sa.Integer(), nullable=True),
    sa.Column('loan_principal', sa.Float(), nullable=True),
    sa.Column('buyout_price', sa.Float(), nullable=True),
    sa.Column('matched_model_id', sa.String(), nullable=True),
    sa.Column('che300_valuation', sa.Float(), nullable=True),
    sa.Column('depreciation_30d', sa.Float(), nullable=True),
    sa.Column('depreciation_60d', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('expected_revenue', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['asset_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommended_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('role_level', sa.String(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('strategy_type', sa.String(), nullable=True),
    sa.Column('recommendation_title', sa.String(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('expected_loss_impact', sa.Float(), nullable=False),
    sa.Column('expected_cashflow_impact', sa.Float(), nullable=False),
    sa.Column('expected_inventory_impact', sa.Float(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('realism_score', sa.Float(), nullable=False),
    sa.Column('resource_need_json', sa.Text(), nullable=True),
    sa.Column('approval_level', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dependencies_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('total_ead', sa.Float(), nullable=False),
    sa.Column('avg_vehicle_value', sa.Float(), nullable=False),
    sa.Column('avg_lgd', sa.Float(), nullable=False),
    sa.Column('avg_recovery_days', sa.Integer(), nullable=False),
    sa.Column('expected_loss_amount', sa.Float(), nullable=False),
    sa.Column('expected_loss_rate', sa.Float(), nullable=False),
    sa.Column('expected_cash_30d', sa.Float(), nullable=False),
    sa.Column('expected_cash_90d', sa.Float(), nullable=False),
    sa.Column('expected_cash_180d', sa.Float(), nullable=False),
    sa.Column('recommended_strategy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['asset_segments.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('success_probability', sa.Float(), nullable=False),
    sa.Column('expected_recovery_gross', sa.Float(), nullable=False),
    sa.Column('towing_cost', sa.Float(), nullable=False),
    sa.Column('inventory_cost', sa.Float(), nullable=False),
    sa.Column('legal_cost', sa.Float(), nullable=False),
    sa.Column('refurbishment_cost', sa.Float(), nullable=False),
    sa.Column('channel_fee', sa.Float(), nullable=False),
    sa.Column('funding_cost', sa.Float(), nullable=False),
    sa.Column('management_cost', sa.Float(), nullable=False),
    sa.Column('discount_cost', sa.Float(), nullable=False),
    sa.Column('net_recovery_pv', sa.Float(), nullable=False),
    sa.Column('expected_loss_amount', sa.Float(), nullable=False),
    sa.Column('expected_loss_rate', sa.Float(), nullable=False),
    sa.Column('expected_recovery_days', sa.Integer(), nullable=False),
    sa.Column('capital_release_score', sa.Float(), nullable=False),
    sa.Column('notes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['asset_segments.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashflow_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=True),
    sa.Column('bucket_day', sa.Integer(), nullable=False),
    sa.Column('gross_cash_in', sa.Float(), nullable=False),
    sa.Column('gross_cash_out', sa.Float(), nullable=False),
    sa.Column('net_cash_flow', sa.Float(), nullable=False),
    sa.Column('discounted_net_cash_flow', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashflow_buckets')
    op.drop_table('strategy_runs')
    op.drop_table('segment_metrics')
    op.drop_table('recommended_actions')
    op.drop_table('assets')
    op.drop_table('valuation_cache')
    op.drop_table('sandbox_results')
    op.drop_table('portfolio_snapshots')
    op.drop_table('management_goals')
    op.drop_table('depreciation_cache')
    op.drop_table('car_models')
    op.drop_table('asset_segments')
    op.drop_table('asset_packages')
    # ### end Alembic commands ###
